<div class="grilleFaction">
  <div class="chef headGrid">Chef</div>
  <div class="guerrier headGrid">Guerrier</div>
  <div class="berseker headGrid">Berseker</div>
  <div class="huscarl headGrid">Huscarl</div>
  <div class="soigneur headGrid">Soigneur</div>
  <div class="chariot headGrid">Chariot</div>
  <div class="zoneBlanche headGrid"></div>
  <div class="cout headGrid">Coût de base</div>
  <div class="protection headGrid">Protections</div>
  <div class="sansProtection headGrid">Sans protection</div>
  <div class="armure headGrid">Armure</div>
  <div class="bouclier headGrid">Bouclier</div>
  <div class="armesClose headGrid">Arme de contact</div>
  <div class="armesImp headGrid">Arme improvisé</div>
  <div class="Lance headGrid">Lance</div>
  <div class="ArmeBase headGrid">Arme standard</div>
  <div class="HacheD headGrid">Hache Danoise</div>
  <div class="armesTir headGrid">Arme de tir</div>
  <div class="fronde headGrid">Fronde</div>
  <div class="javelot headGrid">Javelot</div>
  <div class="arc headGrid">Arc</div>
  <div class="arbalete headGrid">Arbalète</div>
  <div class="equipementSpe headGrid">Equipements spéciales</div>
  <div class="cheval headGrid">Cheval</div>
  <div class="banniere headGrid">Bannière</div>
  <div class="cor headGrid">Cor de guerre</div>
  <div class="chien headGrid">Chien de guerre</div>

  <div class="cout01"></div>
  <div class="cout00"></div>
  <div class="cout02"></div>
  <div class="cout03"></div>
  <div class="cout04"></div>
  <div class="cout05"></div>
  <div class="cout06"></div>
  <div class="cout07"></div>
  <div class="cout08"></div>
  <div class="cout09"></div>
  <div class="cout010"></div>
  <div class="cout011"></div>
  <div class="cout012"></div>
  <div class="cout013"></div>
  <div class="cout014"></div>
  <div class="cout015"></div>

  <div class="cout10"></div>
  <div class="cout11"></div>
  <div class="cout12"></div>
  <div class="cout13"></div>
  <div class="cout14"></div>
  <div class="cout15"></div>
  <div class="cout16"></div>
  <div class="cout17"></div>
  <div class="cout18"></div>
  <div class="cout19"></div>
  <div class="cout110"></div>
  <div class="cout111"></div>
  <div class="cout112"></div>
  <div class="cout113"></div>
  <div class="cout114"></div>
  <div class="cout115"></div>

  <div class="cout20"></div>
  <div class="cout21"></div>
  <div class="cout22"></div>
  <div class="cout23"></div>
  <div class="cout24"></div>
  <div class="cout25"></div>
  <div class="cout26"></div>
  <div class="cout27"></div>
  <div class="cout28"></div>
  <div class="cout29"></div>
  <div class="cout210"></div>
  <div class="cout211"></div>
  <div class="cout212"></div>
  <div class="cout213"></div>
  <div class="cout214"></div>
  <div class="cout215"></div>

  <div class="cout30"></div>
  <div class="cout31"></div>
  <div class="cout32"></div>
  <div class="cout33"></div>
  <div class="cout34"></div>
  <div class="cout35"></div>
  <div class="cout36"></div>
  <div class="cout37"></div>
  <div class="cout38"></div>
  <div class="cout39"></div>
  <div class="cout310"></div>
  <div class="cout311"></div>
  <div class="cout312"></div>
  <div class="cout313"></div>
  <div class="cout314"></div>
  <div class="cout315"></div>

  <div class="cout40"></div>
  <div class="cout41"></div>
  <div class="cout42"></div>
  <div class="cout43"></div>
  <div class="cout44"></div>
  <div class="cout45"></div>
  <div class="cout46"></div>
  <div class="cout47"></div>
  <div class="cout48"></div>
  <div class="cout49"></div>
  <div class="cout410"></div>
  <div class="cout411"></div>
  <div class="cout412"></div>
  <div class="cout413"></div>
  <div class="cout414"></div>
  <div class="cout415"></div>

  <div class="cout50"></div>
  <div class="cout51"></div>
  <div class="cout52"></div>
  <div class="cout53"></div>
  <div class="cout54"></div>
  <div class="cout55"></div>
  <div class="cout56"></div>
  <div class="cout57"></div>
  <div class="cout58"></div>
  <div class="cout59"></div>
  <div class="cout510"></div>
  <div class="cout511"></div>
  <div class="cout512"></div>
  <div class="cout513"></div>
  <div class="cout514"></div>
  <div class="cout515"></div>
</div>
